### ISSUE TITLE
Release 2.0

### ISSUE THREAD

**Issue by theaspect** [CSvetln/SoftwareEngineering#1]
- [x] 1. Код не отформатирован
- [x] 2. Классы перенести в пакет вида com.имя.проект
- [x] 3. В папке src не должно быть скриптов, вынеси их в корень проекта
- [x] 4. Каждый класс должен находиться в своём файле
- [x] 5. В коде не должно быть большой вложенности. В частности 
```
} else {
    if(...){
    }
}
```
можно заменить на 
```
} else if (...){

}
```
- [x] 6. Код возврата из приложения это не print а exitProcess(код). Этот код помещается в  специальную переменную в скрипте $?
- [x] 7. Поля класса Params не меняются, соответственно должны быть val а не var
- [x] 8. Должно быть достаточно одинарных кавычек https://github.com/Lana99/SoftwareEngineering/blob/master/src/Main.kt#L62
- [x] 9. Вот тут должно быть в комментарии подробное описание что за магия происходит https://github.com/Lana99/SoftwareEngineering/blob/master/src/Main.kt#L91
- [x] 10. Добавь тесты когда передаётся только -login и второй когда просто blahblah

**Comment by Lana99** [comment]
1. 80f3097c47a767c53d1fac4686bf1e8981108fcb
2. 93bcf99ccc60b9da4204dfe812668036af6ffa43
3. d497bbff1f2c8c77c4b96e2b7d794226194f7740
4. 064bee8dcda1390d3a312e362725674de0a5b412
5. ca48a3c0f1de73edb9b7e6dcddc9f043dc11c669
6. 98363643a9815351a52508bdec6f680e838dfe0f

**Comment by CSvetln** [comment]
1. 80f3097c47a767c53d1fac4686bf1e8981108fcb
2. 93bcf99ccc60b9da4204dfe812668036af6ffa43
3. d497bbff1f2c8c77c4b96e2b7d794226194f7740
4. 064bee8dcda1390d3a312e362725674de0a5b412
5. ca48a3c0f1de73edb9b7e6dcddc9f043dc11c669
6. 98363643a9815351a52508bdec6f680e838dfe0f
7. 416ad54c15034f816eb00d0ae3b22e93dbb81158
8. 8c54ce221675a6e831bd1e2367969aa881362d8c
9. f15a08e07c0f67dbd67f407dbbc763cf49ab7908
10. 41af78333c2ca516bdf659e57103cdf1ed86555e
