### ISSUE TITLE
Review 2.1

### ISSUE THREAD

**Issue by theaspect** [CSvetln/SoftwareEngineering#2]
- [x] 1. Пакеты состоят только из строчных букв
- [x] 2. Структура папок должна повторять структуру пакетов т.е. класс foo.bar.Baz должен находиться в папке foo/bar
- [x] 3. У тебя ValidateService логически зависит от main и main зависит от ValidateService. Циклические зависимости это очень плохо. Список пользователей передавай через конструктор https://github.com/CSvetln/SoftwareEngineering/blob/master/src/ValidateService.kt#L13
- [x] 4. В классе Main содержится мусор, лишний код (скорее всего он выделен серым цветом) нужно удалить
- [x] 5. Комментарий никуда не годится, нужно объяснить каждую операцию в строках 83-85 https://github.com/CSvetln/SoftwareEngineering/blob/master/src/Main.kt#L84

**Comment by CSvetln** [comment]
1-2. 1c0653b4efcbdd3f46eb345c0673f93f2b87aad1
(извиняюсь, что одним коммитом)
3. 8ccbb46deb981d6f027cef1bc4f09dd32049ee7d
4-5. Я в принципе поменяла метод хеширования на тот, что нашли на занятии
718cf4f43110ba46a09095f0a98091eeae5efb7d
