### ISSUE TITLE
Review 3.0

### ISSUE THREAD

**Issue by theaspect** [CSvetln/SoftwareEngineering#3]
1. (par.res != "") and (par.role != "") нужно вынести в метод класса params и придумать адекватное имя. Вообще таких методов должно быть два для авторизации и аутентификации
2. https://github.com/CSvetln/SoftwareEngineering/blob/master/src/com/main/Main.kt#L11 when становится слишком сложным. Разбей на группы и вынеси в отдельные методы в зависимости от количества переданных параметров (см. пункт 1)
3. Разбирай командную строку при  помощи библиотеки kotlinx.cli https://github.com/CSvetln/SoftwareEngineering/blob/master/src/com/auten/Params.kt#L3
4. В этих полях нет необходимости ты можешь написать private val в конструкторе https://github.com/CSvetln/SoftwareEngineering/blob/master/src/com/auten/ValidateService.kt#L4
5. попробуй заменить на ФВП через метод find https://github.com/CSvetln/SoftwareEngineering/blob/master/src/com/auten/ValidateService.kt#L13
6. можно избавиться от return и сразу написать = https://github.com/CSvetln/SoftwareEngineering/blob/master/src/com/auten/ValidateService.kt#L9 (вот тут пример https://kotlinlang.org/docs/reference/basic-syntax.html 2-й в разделе Functions)
7. Вот эту функцию можно перенести в enum Roles и переписать через ФВП https://github.com/CSvetln/SoftwareEngineering/blob/master/src/com/auten/ValidateService.kt#L25
8. Сделай перегруженный метод isResAccess который будет на вход получать две строки, сплитить их и вызывать isResAccess с двумя коллекциями https://github.com/CSvetln/SoftwareEngineering/blob/master/src/com/auten/ValidateService.kt#L47
9. Что-то мне подсказывает что счетчик тут не нужен, мы можем прервать сравнение на первом несовпадении https://github.com/CSvetln/SoftwareEngineering/blob/master/src/com/auten/ValidateService.kt#L52

**Comment by CSvetln** [comment]
1. 259bc1b21e8a4bfbf2001c5d732634c70611df3f
2. 8f7bd827dbc5191dac9afe2e5ff211447c43f9f7
3. b25010301452eecead18b666e286efe38b2f4940
4. fc95ae1f9b991ffa0adab48be6586357f15be4b8
5. ec4fe3ea8b8fbef5e85e3424dbb30fa611d9ac4c
6. c876f4dafe250284a5687935f13d057451256c9c
7. 8f7bd827dbc5191dac9afe2e5ff211447c43f9f7
8. f5a989468f697421aced2ecb1e574b01dac6327b
9. 0780bb39aba2de821217b11eea12e4b527e146b3
