### ISSUE TITLE
Release 4

### ISSUE THREAD

**Issue by theaspect** [CSvetln/SoftwareEngineering#4]
1. Логины это jdoe, jrow, xxx. Пароли соответственно sup3rpaZZ, Qweqrty12, yyy
https://github.com/CSvetln/SoftwareEngineering/blob/master/src/com/main/Main.kt#L20
2. main в отдельном пакете не очень удачное расположение с точки зрения логики, сервисы дочернее отношение имеют к main, а у тебя это братья. Подними Main.kt на один уровень выше
3. Раздели пакет auten на domain и service
4. isUserHasRole перепиши через ФВП any
5. Доступ к глобальной переменной – раз. Циклическая зависимость – два, Params должен только парсить параметры, ни к каким сервисам обращаться не должен – это три, нарушение принципа IoC это – четыре. И всё в одной строке. (см п 7.) https://github.com/CSvetln/SoftwareEngineering/blob/master/src/com/auten/Params.kt#L24
6. в трех методах isAuthentication, isAuthorisation, isAccounting должно проверяться только наличие необходимых параметров для соответствующего процесса, ни к сервисам ни к списку пользователей не должно быть обращения
7. ValidationService раздели на три части AuthenticationService, AuthorisationService, AccountingService. Скорее всего сервисы друг о друге ничего не будут знать, вся связующая логика будет в main.
8. jar с kotlinx перенеси в папку lib
9. для планов создай папку roadmaps, чтоб не мешались
10. SE.kt и скрипты для него удали, он больше не пригодится

**Comment by CSvetln** [comment]
1. 9edb2b60512422dac380c76d2f2a17fc5e22a295
e462981f0e5be7279738933a99abf0797f5689c3
2. dfa71149e0c2d7a37b3a71ee818af130db33a6dc
3. ca21a61dbd80987ae26800cd8b42749d037f0001
4. a41333dbd67b58d22011ff935c527395be735d7a
(Извиняюсь, что одним коммитом) 
5. 23b265f30ce6fa48dd441b6a2f43251a369b51f1
6.
7.
8. 3d1a5cb3831a05bd32a2ba724ea3855bc27c8679
9. c81dc249e08d6a054435078c9145e56a96f4dec1
10. 900c9fe356dd097f6b99a9231496617186ce84be
Немного подправила скрипты 
2482560e62f7ba1bda072fe2fee23ba215da548a
